variables:
  DOCKER: docker:24.0.6

.configure: &configure
  - apk add curl bash
  - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh

stages:
  - deploy

deploy_dev:
  image: $DOCKER
  stage: deploy
  script:
    - *configure
    - ssh-keyscan -H $DEPLOY_HOST_DEV > ~/.ssh/known_hosts
    - cp .secure_files/id_rsa ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - export DOCKER_HOST="ssh://root@$DEPLOY_HOST_DEV"
    - docker rm -f $(docker ps -aq)
    - docker rmi -f $(docker images -q)
    - cp $DEPLOY_ENV_CONF_DEV .env
    - cp $FE_CONFIG_DEV ./client/.env
    - cp .secure_files/topic-registration-service-firebase-adminsdk-opc81-fb2f0b3a7a.json ./server/src/main/resources/topic-registration-service-firebase-adminsdk-opc81-fb2f0b3a7a.json

    - source go.sh; deploy
  resource_group: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'
