version: "3.8"

volumes:
  nginx_proxy_manager_data:
  letsencrypt:

services:
  backend:
    build:
      dockerfile: ./.build/backend/java/Dockerfile
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/api/v1.0.0/healthcheck/status",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  frontend:
    build:
      dockerfile: ./.build/frontend/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.9.22
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - nginx_proxy_manager_data:/data
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend

  # app:
  #   build:
  #     context: ./.build/nginx
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - frontend
  #   ports:
  #     - 80:80
