server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_db:3306/topic_registration_dev?createDatabaseIfNotExist=true
    username: root
    password: root
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 191541386637-kctjg1nopsvtj3l814h52htasavdji33.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  jwt:
    secretKey: 54e1ac0d-820a-453b-aef5-2840f4b004dd
  security:
    permitAll:
      antPattern: /v3/api-docs/**, /swagger-ui/**, /oauth2/**, /healthcheck/status
    cors:
      allowedOrigin: '*'
      allowedMethods: '*'
      allowedHeaders: '*'
      allowedCredentials: false
      corsConfiguration: '/**'