server:
  port: 8082
  servlet:
    context-path: /api/v1
spring:
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SCHEMA}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  jwt:
    secretKey: ${SECRET_KEY}
  security:
    permitAll:
      antPattern: /v3/api-docs/**, /swagger-ui/**, /oauth2/**, /healthcheck/status, /auth/refresh-token
    cors:
      allowedOrigin: "*"
      allowedMethods: "*"
      allowedHeaders: "*"
      allowedCredentials: false
      corsConfiguration: "/**"
firebase:
  serviceAccount:
  bucketName: ${BUCKET_NAME}
  imageUrl: https://firebasestorage.googleapis.com/v0/b/${firebase.bucketName}/o/%s?alt=media