version: "3.3"

services:
  mysql:
    image: mysql:8
    container_name: mysql-container-dev
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=topic-registration-dev
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-config:/et/mysql/conf.d
    networks:
      - topic-registration-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  topic-registration-server:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: topic-registration-server-container-dev
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "12000:12000"
    networks:
      - topic-registration-network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl -f http://localhost:12001/api/v1/healthcheck/status"]
      timeout: 10s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  nginx:
    image: nginx:1.13
    container_name: nginx-container-dev
    networks:
      - topic-registration-network