pipeline {
    agent any

    tools {
        maven 'maven-3.9.4'
    }

    stages {
        stage('Check tools information') {
            steps {
                echo 'Check tools information'
                sh 'mvn --version'
                sh 'java -version'
            }
        }

        stage('Testing') {
            steps {
                echo 'Switch to server folder'
                sh 'cd server'
                echo 'Running unit test'
                sh 'mvn test'
                echo 'Test cases passed'
            }
        }

        stage('Build docker image') {
            steps {
                echo 'Building docker image'
                sh 'mvn clean install -DskipTests'
            }
        }

        stage('Deployment') {
            steps {
                echo 'Deployment'
            }
        }

    }
}