pipeline {
    agent any

    tools {
        maven 'maven-3.9.4'
    }

    stages {
        stage('Check tools information') {
            steps {
                echo 'Check tools information...'
                sh 'mvn --version'
                sh 'java -version'
            }
        }

        stage('Testing') {
            steps {
                dir('server') {
                    echo 'Running unit test...'
                    sh 'mvn test'
                    echo 'Test cases passed...'
                }
            }
        }

        stage('Build docker image') {
            steps {
                dir('server') {
                    echo 'Building jar file...'
                    sh 'mvn clean install -DskipTests'
                    echo 'Jar file created successfully...'

                    echo 'Building docker image...'
                }
            }
        }

        stage('Deployment') {
            steps {
                echo 'Running docker-compose file...'
            }
        }

    }
}