version: "3.3"

services:
  jenkins-server:
    image: jenkins/jenkins:2.401.3-jdk17
    container_name: jenkins-docker
    networks:
      - jenkins
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
volumes:
  jenkins-docker-certs:
  jenkins-data:
networks:
  jenkins:
